[package]
name = "switchboard-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
switchboard-core = { path = "../switchboard-core" }
switchboard-cef-sys = { path = "../switchboard-cef-sys" }
